# Generated by Django 4.2.2 on 2023-06-27 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MpesaPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formatted_field", models.CharField(max_length=254)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("input_stri", models.CharField(max_length=254)),
                ("county", models.CharField(max_length=20)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
        ),
    ]
